### ISSUE TITLE
Uncaught ReflectionException: Class config does not exist in ...

### ISSUE THREAD

**Issue by moshesm10** [renoki-co/clusteer#20]
Hi!

I did everything according to the instructions, then I wrote a script with the **«Usage»** example 
When I try to run it, an error occurs:

```
PHP Fatal error:  Uncaught ReflectionException: Class config does not exist in /var/www/html/img-gen2/project/vendor/laravel/framework/src/Illuminate/Container/Container.php:873
Stack trace:

#0 /var/www/html/img-gen2/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(873): ReflectionClass->__construct()
#1 /var/www/html/img-gen2/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(754): Illuminate\Container\Container->build()
#2 /var/www/html/img-gen2/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Container\Container->resolve()
#3 /var/www/html/img-gen2/project/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\Container\Container->make()
#4 /var/www/html/img-gen2/project/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(275): app()
#5 /var/www/html/img-gen2/project/vendor/renoki-co/clusteer/src/Clusteer.php(259): config()
#6 /var/www/html/img-gen2/project/vendor/renoki-co/clusteer/src/Clusteer.php(201):  in /var/www/html/img-gen2/project/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 875
```

Am I missing something?

**Comment by rennokki** [comment]
It's a problem with the autoloader. Try deleting the `bootstrap/cache/` folder.

**Comment by rennokki** [comment]
Also, try the following: https://stackoverflow.com/a/54450619/3704404

**Comment by moshesm10** [comment]
> It's a problem with the autoloader. Try deleting the `bootstrap/cache/` folder.

It works, thx!
